wandb_version: 1

activation:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
decay:
  value: 0.0005
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_layers:
  value: 1
input_size:
  value: 784
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
momentum:
  value: 0.7
neurons:
  value: 32
optimizer:
  value: rmsprop
output_activation:
  value: softmax
output_size:
  value: 10
weight_init:
  value: xavier
