wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
decay:
  value: 0.005
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_layers:
  value: 2
input_size:
  value: 784
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.7
neurons:
  value: 64
optimizer:
  value: nag
output_activation:
  value: softmax
output_size:
  value: 10
weight_init:
  value: random
